### ISSUE TITLE
Compilation fails with IRremote library version higher than 3.0.0

### ISSUE THREAD

**Issue by aguedob** [gelanchez/arduino-robot-car#19]
Nothing really relevant, but would be great if you can add this info in the README.md

**Comment by gelanchez** [comment]
@aguedob, thanks for the heads-up. I'll update the code accordingly.

**Comment by gelanchez** [comment]
@aguedob, updated develop branch to run [IRremote 3.3.0](https://github.com/Arduino-IRremote/Arduino-IRremote#converting-your-2x-program-to-the-3x-version).
Now compilation is successful, but it needs testing. Unfortunately, I don't have the robot with me. Could you test is and let me know if you find any issues?

**Comment by aguedob** [comment]
I will test IT and confirm. Thanks!

**Comment by gelanchez** [comment]
Fixed in #20
